# Generated by Django 2.1.1 on 2018-09-06 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180823_0011'),
        ('icarus_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('FAARegistrationNumber', models.TextField()),
                ('remotePilotCertificateNumber', models.TextField()),
                ('mobilePhoneNumber', models.TextField()),
                ('isPhoneNumberAuthenticated', models.BooleanField(default=False)),
            ],
        ),
    ]
