# Generated by Django 2.1.1 on 2018-09-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icarus_backend', '0002_pilot'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
