# Generated by Django 2.1.1 on 2018-09-11 23:07

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_icarususer_picture_url'),
        ('icarus_backend', '0003_drone_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentOfficial',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('area', django.contrib.gis.db.models.fields.PolygonField(default='POLYGON EMPTY', srid=4326)),
            ],
        ),
    ]
