# Generated by Django 2.1.1 on 2018-09-10 18:23

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('icarus_backend', '0003_drone_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirspaceRestriction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('is_constant', models.BooleanField(default=False)),
                ('type', models.TextField()),
                ('description', models.TextField()),
                ('area', django.contrib.gis.db.models.fields.PolygonField(default='POLYGON EMPTY', srid=4326)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
