# Generated by Django 2.1.1 on 2018-09-13 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icarus_backend', '0004_governmentofficial'),
        ('icarus_backend', '0004_airspacerestriction'),
    ]

    operations = [
    ]
