# Generated by Django 2.1.1 on 2018-10-06 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icarus_backend', '0005_merge_20180913_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pilot',
            name='FAARegistrationNumber',
        ),
    ]
