# Generated by Django 2.1.1 on 2018-10-18 20:43

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('icarus_backend', '0006_remove_pilot_faaregistrationnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', django.contrib.gis.db.models.fields.PolygonField(default='POLYGON EMPTY', srid=4326)),
                ('name', models.TextField(unique=True)),
                ('airboss', models.ManyToManyField(related_name='airboss_profile', to=settings.AUTH_USER_MODEL)),
                ('watchCommanders', models.ManyToManyField(related_name='watchcom_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='GovernmentOfficial',
        ),
    ]
