# Generated by Django 2.1.1 on 2018-10-20 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icarus_backend', '0008_auto_20181020_1905'),
    ]

    operations = [
        migrations.RenameModel('Mission', 'Flight'),
        migrations.RenameField('Asset', 'mission', 'flight'),
    ]
