# Generated by Django 2.1.2 on 2018-11-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icarus_backend', '0009_auto_20181020_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='drone',
            name='faa_registration_number',
            field=models.TextField(default='unregistered'),
            preserve_default=False,
        ),
    ]
