# Generated by Django 2.1.1 on 2018-11-27 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icarus_backend', '0010_drone_faa_registration_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulingRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.TextField()),
                ('parameters', models.TextField()),
                ('ends_at', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='scheduling_rule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='icarus_backend.SchedulingRule'),
        ),
    ]
