# Generated by Django 2.1.1 on 2018-11-27 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icarus_backend', '0011_auto_20181127_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='scheduling_rule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='icarus_backend.SchedulingRule'),
        ),
    ]
