# Generated by Django 2.1.1 on 2018-09-07 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180823_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='icarususer',
            name='picture_url',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
